'use client';
import {defaults,type Exercise} from '@/lib/exercises';
import {muscleLabels,targetsFor,variantOptions,referenceExercise,type TargetSelection} from '@/lib/muscle-targets';
import {ExerciseSearch} from './exercise-search';
import {Choice} from './training-panels';
export function MuscleInfo({exercise,selection={},onChange}:{exercise:Exercise;selection?:TargetSelection;onChange?:(selection:TargetSelection)=>void}){
 const target=targetsFor(exercise,selection);const variants=variantOptions(exercise,selection);const isCustom=!defaults.some(e=>e.id===exercise.id);const reference=referenceExercise(exercise,selection);
 return <section className="muscle-info"><h4>Bu hareket nereyi çalıştırır?</h4>
 {target.known&&<dl><div><dt>Ana hedef</dt><dd>{target.primary.map(m=>muscleLabels[m]).join(' · ')}</dd></div><div><dt>Bölgesel vurgu</dt><dd>{target.emphasis.length?target.emphasis.map(m=>muscleLabels[m]).join(' · '):'Özel bir alt bölge vurgusu belirtilmedi'}</dd></div>{target.secondary.length>0&&<div><dt>Yardımcı kaslar</dt><dd>{target.secondary.map(m=>muscleLabels[m]).join(' · ')}</dd></div>}</dl>}
 {target.note&&<p>{target.note}</p>}
 {onChange&&variants.length>0&&<div className="muscle-variant"><label>Bu antrenmandaki açı / yön</label><Choice label="Hareketin açısı veya çekiş yönü" value={selection.targetVariant||'unspecified'} items={variants} onChange={targetVariant=>onChange({...selection,targetVariant})}/></div>}
 {onChange&&isCustom&&<details><summary>{reference?'Katalog eşleştirmesi: '+reference.name:'Hedef bilgisi için katalogla eşleştir'}</summary><p>Yalnızca yaptığın hareketle aynı olanı seç. Eşleşmiyorsa boş bırak.</p><ExerciseSearch label="Aynı hareketi katalogda bul" exercises={defaults} selectedId={selection.targetExerciseId} restoreFocusOnChoose onChoose={targetExerciseId=>onChange({targetExerciseId})}/>{selection.targetExerciseId&&<button type="button" className="textbtn" onClick={()=>onChange({})}>Eşleştirmeyi kaldır</button>}</details>}
 {onChange&&(variants.length>0||isCustom)&&<p className="muscle-scope">Seçim bu antrenmandaki bu hareketin tüm setlerine uygulanır.</p>}
 </section>;
}
export function MuscleSources(){return <details className="muscle-sources"><summary>Harita nasıl yorumlanır?</summary><p>Hareket adı ve kaydettiğin açıdan oluşturulan genel anatomik rehberdir; kişisel kas aktivasyonu veya kas gelişimi ölçümü değildir. Teknik, tutuş ve hareket açıklığı sonucu değiştirir. Boyanmayan alan “hiç çalışmadı” anlamına gelmez. Küçük / derin kasların tamamı çizimde bulunmaz; brachialis ve kalça bükücüler yaklaşık konumlarıyla gösterilir.</p><p>Set sayıları kaydettiğin hareketlerin setleridir. Bir set birden çok kasa katkı verebilir; bölge sayılarını toplayarak toplam antrenman seti hesaplama. Yardımcı katkı doğrudan setle eşdeğer değildir.</p><a href="https://www.nasm.org/workout-exercise-guidance" target="_blank" rel="noreferrer">NASM hareket kütüphanesi</a><a href="https://pubmed.ncbi.nlm.nih.gov/33049982/" target="_blank" rel="noreferrer">Bench açısı ve göğüs aktivasyonu</a><a href="https://www.acefitness.org/continuing-education/prosource/january-2016/5767/ace-technique-series-romanian-deadlift/" target="_blank" rel="noreferrer">ACE · Romanian deadlift</a><a href="https://pubmed.ncbi.nlm.nih.gov/35819335/" target="_blank" rel="noreferrer">Baş üstü triceps çalışması</a></details>}
