import assert from 'node:assert/strict';
import {activeCalories,caloriesFor,dailyCalories,isRecord,cardioTypes} from '../lib/training.ts';
const profile={id:'user-profile-v1',kind:'profile',updated:1,age:25,height:175,weight:96};
assert(isRecord(profile));assert(!isRecord({...profile,weight:-1}));assert(!isRecord({...profile,age:25.5}));
const legacy={id:'old',kind:'workout',date:'2026-09-30T07:00:00Z',ended:'2026-09-30T08:00:00Z',updated:1,entries:[{exerciseId:'Göğüs-1',sets:[{id:'set1',weight:18,reps:12}]}]};
assert(isRecord(legacy));assert.equal(caloriesFor(legacy),null);
const walking={id:'cardio1',type:'walking',label:'Yürüme',optionId:'walk-medium',effort:'Düz zemin, normal',met:3.8,minutes:30};
const combined={...legacy,id:'combined',cardio:[walking],calorie:{weight:96,height:175,age:25,strengthMinutes:45,strengthMet:3.5,method:'met-net-v1'}};
assert(isRecord(combined));assert.deepEqual(caloriesFor(combined),{resistance:189,mat:0,strength:189,cardio:141,total:330,minutes:75});
assert(Math.abs(activeCalories(3.8,96,30)-141.12)<0.00001);
assert.equal(activeCalories(1,96,30),0);assert.equal(activeCalories(3.8,96,-2),0);
const cardioOnly={...combined,id:'cardio-only',entries:[],calorie:{...combined.calorie,strengthMinutes:0}};
assert.deepEqual(caloriesFor(cardioOnly),{resistance:0,mat:0,strength:0,cardio:141,total:141,minutes:30});
assert.equal(dailyCalories([legacy,combined,cardioOnly,{...combined,id:'draft',ended:undefined}])[0].total,471);
assert.equal(dailyCalories([legacy,combined,cardioOnly])[0].count,2);
profile.weight=85;assert.equal(caloriesFor(combined).total,330);
assert(!isRecord({...combined,cardio:[{...walking,minutes:-1}]}));
assert(!isRecord({...combined,calorie:{...combined.calorie,strengthMinutes:Infinity}}));
assert(isRecord(JSON.parse(JSON.stringify(combined))));
assert.equal(new Set(cardioTypes.map(c=>c.id)).size,4);
console.log('PASS: profile validation; old records without invented calories; mixed/cardio-only calculations; daily aggregation; historical weight snapshots; backup round-trip; invalid inputs.');
const edited={...combined,cardio:[{...walking,minutes:60}],calorie:{...combined.calorie,strengthMinutes:60}};
assert.deepEqual(caloriesFor(edited),{resistance:252,mat:0,strength:252,cardio:282,total:534,minutes:120});
assert.equal(dailyCalories([edited])[0].strength,252);assert.equal(dailyCalories([edited])[0].cardio,282);
const deleted={...edited,deleted:true,updated:3};
assert(isRecord(deleted));assert.equal(caloriesFor(deleted),null);assert.equal(dailyCalories([deleted]).length,0);
assert.equal(dailyCalories([deleted,cardioOnly])[0].total,141);
assert.equal(caloriesFor({...edited,entries:[]}).strength,0);
const versionMap=new Map();for(const r of [deleted,{...combined,updated:1}]){const old=versionMap.get(r.id);if(!old||r.updated>old.updated)versionMap.set(r.id,r)}assert.equal(versionMap.get(deleted.id).deleted,true);
console.log('PASS: edits recalculate strength + cardio; deletion removes calories; stale sync cannot resurrect deletion; removing all strength sets removes strength calories.');
