'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
import {Dumbbell,Activity,Clock3,BarChart3,Plus,Check,ChevronLeft,ChevronRight,X,Download,Upload,CloudCheck,CloudOff,Settings2,Trash2,Flame,HeartPulse,UserRound,Pencil} from 'lucide-react';
import {defaults,groups,mergeExerciseCatalog,removeExercisePermanently,visibleExercises,archivedExercises,trackingFor,trackingOptions,matGroup,inExerciseGroup,exerciseSummary,type TrackingMode,type Exercise} from '@/lib/exercises';
import {HistoryActivities} from '@/components/history-activities';
import {DailyMotivation} from '@/components/daily-motivation';
import {isRecord,caloriesFor,dailyCalories,setLabel,setMode,setMetric,type Profile,type Cardio,type Workout,type RecordItem} from '@/lib/training';
import {ExerciseSearch} from '@/components/exercise-search';
import {correctExerciseRecord} from '@/lib/record-corrections';
import {BodyMap} from '@/components/body-map';
import {MuscleInfo} from '@/components/muscle-info';
import {ExerciseGallery} from '@/components/exercise-visual';
import {PhotoPicker,SwipeExercise,DeleteExercise} from '@/components/exercise-management';
import type {TargetSelection} from '@/lib/muscle-targets';
import {WorkoutEditor,DeleteWorkout} from '@/components/workout-editor';
import {Choice,ProfilePanel,CardioPanel,FinishPanel,CalorieReport} from '@/components/training-panels';
const uid=()=>crypto.randomUUID();
const dateLabel=(d:string)=>new Date(d).toLocaleDateString('tr-TR',{day:'numeric',month:'long'});
const n=(x:number)=>x.toLocaleString('tr-TR',{maximumFractionDigits:1});
export default function Home(){
 const [records,setRecords]=useState<RecordItem[]>([]),[ready,setReady]=useState(false),[tab,setTab]=useState('train'),[group,setGroup]=useState<string|null>(null),[selected,setSelected]=useState<string|null>(null),[status,setStatus]=useState('Hazırlanıyor'),[notice,setNotice]=useState(''),[settings,setSettings]=useState(false),[adding,setAdding]=useState(false),[weight,setWeight]=useState(''),[reps,setReps]=useState(''),[name,setName]=useState(''),[unit,setUnit]=useState('Makinede görünen'),[reportId,setReportId]=useState(defaults[0].id),[detail,setDetail]=useState<string|null>(null),[query,setQuery]=useState(''),[offlineReady,setOfflineReady]=useState(false);
 const [profileOpen,setProfileOpen]=useState(false),[cardioOpen,setCardioOpen]=useState(false),[finishId,setFinishId]=useState<string|null>(null);
 const [editId,setEditId]=useState<string|null>(null),[deleteId,setDeleteId]=useState<string|null>(null);
 const [purgeExercise,setPurgeExercise]=useState<Exercise|null>(null);
 const [removeExercise,setRemoveExercise]=useState<Exercise|null>(null),[newPhoto,setNewPhoto]=useState<string|null|undefined>(undefined),[photoBusy,setPhotoBusy]=useState(false);
 const [newTracking,setNewTracking]=useState<TrackingMode>('weighted'),[newGroup,setNewGroup]=useState('Karın'),[reportMode,setReportMode]=useState<TrackingMode>('weighted');
 const [targetSelection,setTargetSelection]=useState<TargetSelection>({});
 const current=useRef<RecordItem[]>([]),pending=useRef<Record<string,RecordItem>>({}),busy=useRef(false),file=useRef<HTMLInputElement>(null);
 const profile=records.find((r):r is Profile=>r.kind==='profile');
 const finishing=records.find((r):r is Workout=>r.kind==='workout'&&r.id===finishId);
 const exercises=mergeExerciseCatalog(records.filter((r):r is Exercise=>r.kind==='exercise'));
 const workouts=records.filter((r):r is Workout=>r.kind==='workout'&&!r.deleted).sort((a,b)=>b.date.localeCompare(a.date));
 const active=workouts.find(w=>!w.ended),history=workouts.filter(w=>w.ended),exercise=exercises.find(e=>e.id===selected);
 const editing=workouts.find(w=>w.id===editId),deleting=workouts.find(w=>w.id===deleteId);
 const todayTotals=dailyCalories(history).find(p=>new Date(p.date).toDateString()===new Date().toDateString());
 const setCount=(w:Workout)=>w.entries.reduce((a,e)=>a+e.sets.length,0);
 function cache(all:RecordItem[],queue:Record<string,RecordItem>){try{localStorage.setItem('setdefteri-cache',JSON.stringify({records:all,pending:queue}));return true}catch{setNotice('Telefon depolaması dolu veya kullanılamıyor. Kayıt yapmadan önce alan aç.');return false}}
 async function sync(){if(busy.current||!navigator.onLine)return;busy.current=true;const batch=Object.values(pending.current);setStatus('Yedekleniyor');try{const res=await fetch('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({records:batch})});if(!res.ok)throw Error(String(res.status));const data=await res.json() as {records:RecordItem[]};for(const r of batch)if(pending.current[r.id]?.updated===r.updated)delete pending.current[r.id];const merged=new Map<string,RecordItem>();for(const r of [...data.records,...current.current]){const old=merged.get(r.id);if(!old||r.updated>old.updated)merged.set(r.id,r)}current.current=[...merged.values()];cache(current.current,pending.current);setRecords(current.current);setStatus(Object.keys(pending.current).length?'Yedekleme bekliyor':'Yedeklendi')}catch{setStatus(navigator.onLine?'Yedekleme bekliyor':'Çevrimdışı')}finally{busy.current=false}}
 function save(r:RecordItem){r={...r,updated:Math.max(Date.now(),(current.current.find(x=>x.id===r.id)?.updated||0)+1)};const all=[...current.current.filter(x=>x.id!==r.id),r];const queue={...pending.current,[r.id]:r};if(!cache(all,queue))return false;current.current=all;pending.current=queue;setRecords(all);setStatus('Telefona kaydedildi');void sync();return true}
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('setdefteri-cache')||'{}');pending.current=saved.pending||{};current.current=(saved.records||[]).filter(isRecord).map((r:RecordItem)=>{const corrected=correctExerciseRecord(r);if(corrected!==r)pending.current[r.id]=corrected;return corrected});cache(current.current,pending.current);setRecords(current.current)}catch{setNotice('Yerel kayıt okunamadı. Yedeklerin bağlantı kurulunca yüklenecek.')}setReady(true);void sync();const online=()=>void sync(),offline=()=>setStatus('Çevrimdışı');window.addEventListener('online',online);window.addEventListener('offline',offline);const timer=setInterval(sync,20000);if(!navigator.onLine)setStatus('Çevrimdışı');if('serviceWorker' in navigator){navigator.serviceWorker.register('/sw.js').then(()=>navigator.serviceWorker.ready).then(reg=>{const urls=performance.getEntriesByType('resource').map(r=>r.name).filter(u=>u.startsWith(location.origin)&&/\.(js|css)(\?|$)/.test(u));reg.active?.postMessage({type:'CACHE_SHELL',urls});setOfflineReady(true)}).catch(()=>setOfflineReady(false))}return()=>{clearInterval(timer);window.removeEventListener('online',online);window.removeEventListener('offline',offline)}},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_workout_history',title:'Antrenman geçmişini oku',description:'Kayıtlı antrenmanları ve özel hareketleri okur. Kayıt değiştirmez.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Boş nesne gerekiyor');return {records:current.current}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t)}},[notice]);
 function choose(id:string){setSelected(id);const existing=active?.entries.find(e=>e.exerciseId===id);setTargetSelection({targetExerciseId:existing?.targetExerciseId,targetVariant:existing?.targetVariant});const prev=history.find(w=>w.entries.some(e=>e.exerciseId===id));const last=existing?.sets.at(-1)||prev?.entries.find(e=>e.exerciseId===id)?.sets.at(-1);const m=trackingFor(exercises.find(e=>e.id===id));setWeight(last?String(last.weight):'');setReps(last&&setMode(last)===m?String(m==='timed'?last.seconds:last.reps):'')}
 function updateTarget(selection:TargetSelection){if(active?.entries.some(e=>e.exerciseId===selected)){if(!save({...active,entries:active.entries.map(e=>e.exerciseId===selected?{...e,targetExerciseId:selection.targetExerciseId,targetVariant:selection.targetVariant}:e)}))return}setTargetSelection(selection)}
 function addSet(){if(!exercise)return;const mode=trackingFor(exercise),w=mode==='weighted'?Number(weight.replace(',','.')):0,r=Number(reps);if((mode==='weighted'&&weight.trim()==='')||reps.trim()===''||!Number.isFinite(w)||w<0||w>2000||!Number.isInteger(r)||r<1||r>(mode==='timed'?36000:1000)){setNotice(mode==='timed'?'1–36000 arasında tam saniye gir.':'Geçerli ağırlık ve 1–1000 arası tam tekrar sayısı gir.');return}const workout:Workout=active?structuredClone(active):{id:uid(),kind:'workout',date:new Date().toISOString(),entries:[],updated:0};let entry=workout.entries.find(e=>e.exerciseId===selected);if(!entry){entry={exerciseId:selected!,sets:[],...targetSelection};workout.entries.push(entry)}entry.sets.push({id:uid(),weight:w,reps:mode==='timed'?1:r,mode,...(mode==='timed'?{seconds:r}:{})});if(save(workout))setNotice('Set kaydedildi')}

 function finish(w=active){if(!w)return;setFinishId(w.id);if(!profile)setProfileOpen(true)}
 function complete(w:Workout){if(save(w)){setFinishId(null);setSelected(null);setGroup(null);setTab('history');setDetail(w.id);setNotice(`Antrenman kaydedildi · yaklaşık ${caloriesFor(w)?.total||0} aktif kcal`)}}
 function deleteWorkout(w:Workout){if(save({...w,deleted:true})){setDeleteId(null);setEditId(null);setDetail(null);setNotice('Antrenman silindi; günlük toplamlar güncellendi')}}
 function saveCardio(c:Cardio){const w:Workout=active?structuredClone(active):{id:uid(),kind:'workout',date:new Date().toISOString(),entries:[],updated:0};w.cardio=[...(w.cardio||[]),c];if(save(w)){setCardioOpen(false);setNotice('Kardiyo kaydedildi')}}
 function openCardio(){if(!profile){setProfileOpen(true);setCardioOpen(true)}else setCardioOpen(true)}
 function addExercise(){if(photoBusy||!name.trim()||!group)return;const e:Exercise={id:uid(),kind:'exercise',name:name.trim(),group:group===matGroup?newGroup:group,unit,tracking:newTracking,updated:0,photoData:newPhoto};if(save(e)){setAdding(false);setName('');setNewPhoto(undefined);choose(e.id)}}
 function download(data:string,type:string,filename:string){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function exportToFiles(){
 const data=JSON.stringify({version:1,records:current.current},null,2);
 const backup=new File([data],'set-defteri-yedek.json',{type:'application/json'});
 try{if(navigator.canShare?.({files:[backup]})){await navigator.share({files:[backup],title:'Set Defteri yedeği'});return}}catch(e){if((e as Error).name==='AbortError')return;}
 download(data,'application/json','set-defteri-yedek.json');setNotice('Yedek indirildi. Dosyalar uygulamasından iCloud Drive’a taşıyabilirsin.');
 }
 function csv(){const rows=[['Tarih','Bölge','Hareket','Ağırlık tanımı','Set','kg','Tekrar','Saniye','Kayıt türü']];for(const w of history)for(const e of w.entries){const ex=exercises.find(x=>x.id===e.exerciseId);e.sets.forEach((s,i)=>rows.push([dateLabel(w.date),ex?.group||'',ex?.name||'',ex?.unit||'',String(i+1),setMode(s)==='weighted'?String(s.weight):'',setMode(s)==='timed'?'':String(s.reps),String(s.seconds||''),setMode(s)]))}download('\uFEFF'+rows.map(row=>row.map(s=>'"'+s.replaceAll('"','""')+'"').join(';')).join('\r\n'),'text/csv;charset=utf-8','set-defteri-rapor.csv')}
 async function restore(f?:File){if(!f)return;try{const data=JSON.parse(await f.text());if(data.version!==1||!Array.isArray(data.records)||data.records.length>500)throw Error();for(const r of data.records){if(!isRecord(r))throw Error()}if(!confirm('Yedekteki kayıtlar mevcut kayıtlarınla birleştirilsin mi?'))return;const map=new Map(current.current.map(r=>[r.id,r]));for(const r of data.records)if(!map.has(r.id)||r.updated>map.get(r.id)!.updated)map.set(r.id,r);const all=[...map.values()],queue={...pending.current};for(const r of all)queue[r.id]=r;if(cache(all,queue)){current.current=all;pending.current=queue;setRecords(all);void sync();setNotice('Yedek içe aktarıldı')}}catch{setNotice('Bu dosya geçerli bir Set Defteri yedeği değil.')}if(file.current)file.current.value=''}
 const entries=active?.entries.find(e=>e.exerciseId===selected)?.sets||[];
 const previous=history.find(w=>w.entries.some(e=>e.exerciseId===selected));
 const points=history.filter(w=>w.entries.some(e=>e.exerciseId===reportId)).reverse().map(w=>({date:w.date,sets:w.entries.find(e=>e.exerciseId===reportId)!.sets.filter(s=>setMode(s)===reportMode)})).filter(p=>p.sets.length);
 const recent=history.filter(w=>Date.now()-new Date(w.date).getTime()<7*86400000);
 return <div className="app"><header><a className="brand" href="/" aria-label="Set Defteri ana sayfa"><span className="brandmark"><Dumbbell size={23}/></span><span>SET<span className="thin">DEFTERİ</span></span></a><button className="icon" onClick={()=>setSettings(true)} aria-label="Ayarlar ve yedekleme"><Settings2 size={21}/></button></header>
 <main><div className="topline"><span>KİŞİSEL ANTRENMAN GÜNLÜĞÜ</span><span className="sync">{status==='Yedeklendi'?<CloudCheck size={14}/>:<CloudOff size={14}/>} {status}</span></div>
 <DailyMotivation ready={ready} onStart={()=>{setTab('train');setGroup(null);if(!profile)setProfileOpen(true)}}/>
 {!ready?<div className="empty">Kayıtların yükleniyor…</div>:<>
 {tab==='train'&&<><div className="titleline"><div><p className="eyebrow">{new Date().toLocaleDateString('tr-TR',{day:'numeric',month:'long',weekday:'long'})}</p><h1>{group?group:'Bugün ne çalışıyoruz?'}</h1></div><span className="sectionnum">01</span></div>
 {active&&<div className="session"><div><span className="live">ANTRENMAN DEVAM EDİYOR</span><strong>{active.entries.filter(e=>e.sets.length).length} hareket <span>·</span> {setCount(active)} set{!!active.cardio?.length&&<> <span>·</span> {active.cardio.reduce((s,c)=>s+c.minutes,0)} dk kardiyo</>}</strong></div><button onClick={()=>finish()} className="smallbtn" disabled={!setCount(active)&&!active.cardio?.length}>Bitir <Check size={16}/></button></div>}
 <div className="daily-calorie-card"><span>BUGÜN · TAMAMLANAN ANTRENMANLAR</span><strong>≈ {todayTotals?.total||0} <small>aktif kcal</small></strong><div className="calorie-parts"><span>Kuvvet / mat <b>{todayTotals?.strength||0}</b> kcal</span><span>+</span><span>Kardiyo <b>{todayTotals?.cardio||0}</b> kcal</span></div>{active&&<p>Devam eden antrenmanın, bitirip süreyi kaydettiğinde bu toplama eklenecek.</p>}{history.some(w=>new Date(w.date).toDateString()===new Date().toDateString()&&!w.calorie)&&<p>Bugünkü bazı kayıtlarda süre eksik. Geçmişten “Kalori bilgisi ekle”yi kullan.</p>}</div>
 {active&&<div className="edit-actions session-actions"><button className="outline" onClick={()=>setEditId(active.id)}><Pencil size={16}/> Düzenle</button><button className="outline danger-text" onClick={()=>setDeleteId(active.id)}><Trash2 size={16}/> Antrenmanı sil</button></div>}
 {!profile&&<button className="profile-prompt" onClick={()=>setProfileOpen(true)}><UserRound size={20}/><span>Kalori hesabı için profilini tamamla<small>Kilo, boy ve yaş bilgilerini ekle.</small></span><ChevronRight size={18}/></button>}
 {group?<><button className="back" onClick={()=>{setGroup(null);setQuery('')}}><ChevronLeft size={18}/> Tüm bölgeler</button><div className="searchrow"><input placeholder="Hareket ara…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Hareket ara"/></div><p className="swipe-hint">Silmek için hareketi sola kaydır veya ••• düğmesine dokun.</p><div className="exercise-list">{visibleExercises(exercises).filter(e=>inExerciseGroup(e,group)&&e.name.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))).sort((a,b)=>a.name.localeCompare(b.name,'tr',{sensitivity:'base',numeric:true})).map(e=><SwipeExercise key={e.id} exercise={e} onChoose={()=>choose(e.id)} onDelete={()=>setRemoveExercise(e)}/>)}</div><details className="archived-exercises"><summary>Silinen hareketler ({archivedExercises(exercises).filter(e=>inExerciseGroup(e,group)).length})</summary>{archivedExercises(exercises).filter(e=>inExerciseGroup(e,group)).map(e=><div key={e.id}><span>{e.name}</span><button type="button" className="textbtn" onClick={()=>save({...e,archived:false})}>Geri getir</button><button type="button" className="textbtn danger-text" onClick={()=>setPurgeExercise(e)}>Kalıcı sil</button></div>)}</details><button className="outline wide" onClick={()=>{setNewPhoto(undefined);setNewTracking(group===matGroup?'bodyweight':'weighted');setAdding(true)}}><Plus size={18}/> Yeni hareket ekle</button></>:<><ExerciseSearch exercises={exercises} onChoose={choose} label="Tüm hareketlerde ara"/><p className="sub">İstersen bölge seçerek de devam edebilirsin.</p><div className="regions">{groups.map((g,i)=><button key={g} onClick={()=>setGroup(g)} className={'region region-'+i}><span className="regiontop"><span>{String(i+1).padStart(2,'0')}</span><ChevronRight size={19}/></span><strong>{g}</strong><small>{visibleExercises(exercises).filter(e=>e.group===g).length} hareket</small></button>)}</div><button className="cardio-card mat-card" onClick={()=>{setGroup(matGroup);setQuery('')}}><Activity size={28}/><span><strong>Mat / Vücut ağırlığı</strong><small>Kalça köprüsü · Mekik · Plank</small></span><Plus size={23}/></button><button className="cardio-card" onClick={openCardio}><HeartPulse size={28}/><span><strong>Kardiyo</strong><small>Yürüme · Bisiklet · Yüzme · Koşma</small></span><Plus size={23}/></button><div className="tip"><Activity size={21}/><p>Her set bir adım.<span>Önceki performansın, hareket ekranında yanında.</span></p></div></>}
 {active&&active.entries.some(e=>e.sets.length>0)&&<section className="today"><div className="sectionhead"><h2>Bugünkü setlerin</h2><span>{n(setCount(active))} SET</span></div>{active.entries.filter(e=>e.sets.length).map(e=><button className="todayrow" key={e.exerciseId} onClick={()=>choose(e.exerciseId)}><div><strong>{exercises.find(x=>x.id===e.exerciseId)?.name}</strong><small>{e.sets.map(s=>setLabel(s)).join(' / ')}</small></div><ChevronRight size={18}/></button>)}</section>}{active&&!!active.cardio?.length&&<section className="today"><div className="sectionhead"><h2>Bugünkü kardiyo</h2><button className="icon" aria-label="Kardiyo ekle" onClick={openCardio}><Plus size={19}/></button></div>{active.cardio.map(c=><div className="todayrow cardio-row" key={c.id}><div><strong>{c.label} · {c.minutes} dk</strong><small>{c.effort}</small></div><button className="icon muted" aria-label="Kardiyo kaydını sil" onClick={()=>{if(confirm('Bu kardiyo kaydı silinsin mi?'))save({...active,cardio:active.cardio?.filter(x=>x.id!==c.id)})}}><Trash2 size={17}/></button></div>)}</section>}</>}
 {tab==='history'&&<><div className="titleline"><div><p className="eyebrow">EMEĞİNİN KAYDI</p><h1>Antrenman geçmişi</h1></div><span className="sectionnum">02</span></div><p className="sub">Tamamladığın her antrenman burada.</p>{!history.length?<div className="empty"><Clock3 size={36}/><h2>İlk kaydını bekliyor</h2><p>Setlerini kaydedip antrenmanını bitirdiğinde burada göreceksin.</p><button className="primary" onClick={()=>setTab('train')}>Antrenmana geç</button></div>:history.map(w=><article className="historycard" key={w.id}><button className="historytitle" onClick={()=>setDetail(detail===w.id?null:w.id)}><div><span className="eyebrow">{new Date(w.date).toLocaleDateString('tr-TR',{weekday:'long',year:'numeric'})}</span><h2>{dateLabel(w.date)}</h2><p>{[...new Set(w.entries.filter(e=>e.sets.length).map(e=>exercises.find(x=>x.id===e.exerciseId)?.group))].join(' · ')}{!!w.cardio?.length&&<> · Kardiyo</>}</p><p className="history-calorie">{caloriesFor(w)?`≈ ${caloriesFor(w)!.total} kcal · tahmini aktif`:'Kalori bilgisi eklenmedi'}</p></div><div className="count"><strong>{setCount(w)}</strong><small>SET</small></div></button>{detail===w.id&&<div className="historydetails"><HistoryActivities workout={w} exercises={exercises}/>{w.calorie&&<p className="sub">{w.calorie.weight} kg ile hesaplandı · Ağırlık {w.calorie.strengthMinutes} dk ({caloriesFor(w)?.resistance} kcal)</p>}<div className="edit-actions"><button className="outline" onClick={()=>setEditId(w.id)}><Pencil size={16}/> Düzenle / hareket ekle</button><button className="outline danger-text" onClick={()=>setDeleteId(w.id)}><Trash2 size={16}/> Sil</button></div><button className="outline wide" onClick={()=>finish(w)}><Flame size={18}/>{w.calorie?'Kalori bilgisini düzenle':'Kalori bilgisi ekle'}</button><BodyMap workout={w} exercises={exercises}/></div>}</article>)}</>}
 {tab==='reports'&&<><div className="titleline"><div><p className="eyebrow">RAKAMLARLA SEN</p><h1>Gelişimin</h1></div><span className="sectionnum">03</span></div><div className="stats"><div><span>SON 7 GÜN</span><strong>{recent.length}</strong><small>antrenman</small></div><div><span>SON 7 GÜN</span><strong>{recent.reduce((a,w)=>a+setCount(w),0)}</strong><small>tamamlanan set</small></div><div><span>BAŞLANGIÇTAN BERİ</span><strong>{history.length}</strong><small>antrenman</small></div></div><section className="reportcard"><div className="sectionhead"><h2>Hareket gelişimi</h2><BarChart3 size={20}/></div><ExerciseSearch exercises={exercises} includeArchived selectedId={reportId} onChoose={id=>{setReportId(id);const last=history.flatMap(w=>w.entries.filter(e=>e.exerciseId===id).flatMap(e=>e.sets)).at(0);setReportMode(last?setMode(last):trackingFor(exercises.find(e=>e.id===id)))}} label="Gelişimini görmek istediğin hareket"/><div className="formfield">Gelişim ölçütü<Choice label="Gelişim ölçütü" value={reportMode} onChange={v=>setReportMode(v as TrackingMode)} items={trackingOptions}/></div><p className="sub">Antrenman başına en yüksek {reportMode==='timed'?'süre (sn)':reportMode==='bodyweight'?'tekrar':'ağırlık (kg)'}. Farklı kayıt türleri ayrı gösterilir.</p>{points.length?<><div className="chart">{points.slice(-8).map((p,i)=>{const best=Math.max(...p.sets.map(s=>setMetric(s,reportMode)));const max=Math.max(1,...points.slice(-8).flatMap(p=>p.sets.map(s=>setMetric(s,reportMode))));return <div className="barcol" key={p.date}><strong>{n(best)}</strong><div className="bar" style={{height:Math.max(4,best/max*130)}}/><small>{new Date(p.date).toLocaleDateString('tr-TR',{day:'numeric',month:'numeric'})}</small></div>})}</div><div className="reportrows">{points.slice(-8).reverse().map(p=><div key={p.date}><span>{dateLabel(p.date)}</span><strong>{p.sets.map(s=>setLabel(s)).join(' / ')}</strong></div>)}</div></>:<div className="empty compact"><BarChart3 size={32}/><p>Bu hareketi kaydettiğinde gelişim grafiğin burada oluşacak.</p></div>}</section><CalorieReport workouts={history}/><button className="outline wide" disabled={!history.length} onClick={csv}><Download size={18}/> Raporu indir (CSV)</button></>}
 </>}
 </main><nav className="bottomnav" aria-label="Ana menü">{[['train','Antrenman',Dumbbell],['history','Geçmiş',Clock3],['reports','Gelişim',BarChart3]].map(([id,label,Icon]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setGroup(null)}}><Icon size={22}/><span>{label}</span></button>)}</nav>
 {selected&&exercise&&<Dialog open onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="sheet" showCloseButton={false} aria-describedby={undefined}><div className="handle"/><div className="sheethead"><span className="eyebrow">{exercise.group}</span><button className="icon" aria-label="Kapat" onClick={()=>setSelected(null)}><X/></button></div><DialogTitle id="exercise-title">{exercise.name}</DialogTitle><p className="sub">{exerciseSummary(exercise)}</p><div className="formfield">Nasıl kaydedeceksin?<Choice label="Hareket kayıt türü" value={trackingFor(exercise)} items={trackingOptions} onChange={v=>{if(save({...exercise,tracking:v as TrackingMode})){setReps('');setWeight('')}}}/><small>Yeni setlere uygulanır. Eski setleri Geçmiş → Düzenle’den değiştirebilirsin.</small></div><ExerciseGallery key={exercise.id+exercise.updated+JSON.stringify(targetSelection)} exercise={exercise} selection={targetSelection}/><PhotoPicker key={exercise.id} value={exercise.photoData} onChange={photoData=>{if(save({...exercise,photoData}))setNotice(photoData===null?'Görsel kaldırıldı':photoData?'Fotoğraf kaydedildi':'Katalog görseline dönüldü')}}/><MuscleInfo exercise={exercise} selection={targetSelection} onChange={updateTarget}/><div className="previous"><Clock3 size={18}/><div><span>ÖNCEKİ ANTRENMAN {previous&&'· '+dateLabel(previous.date)}</span><strong>{previous?previous.entries.find(e=>e.exerciseId===selected)?.sets.map(s=>setLabel(s)).join(' / '):'İlk kaydınla başlayalım.'}</strong></div></div><div className="settable"><div className="setheader simple-set"><span>SET</span><span>KAYIT</span><span/></div>{entries.map((s,i)=><div className="setrow simple-set" key={s.id}><span className="setindex">{i+1}</span><strong>{setLabel(s)}</strong><button aria-label={`${i+1}. seti sil`} className="icon muted" onClick={()=>{if(active&&confirm('Bu set silinsin mi?'))save({...active,entries:active.entries.map(e=>e.exerciseId===selected?{...e,sets:e.sets.filter(x=>x.id!==s.id)}:e)})}}><Trash2 size={17}/></button></div>)}</div><form onSubmit={e=>{e.preventDefault();addSet()}}><div className={'setinputs'+(trackingFor(exercise)==='weighted'?'':' unweighted-inputs')}><span className="setindex">{entries.length+1}</span>{trackingFor(exercise)==='weighted'&&<label><span>Ağırlık (kg)</span><input required autoComplete="off" inputMode="decimal" placeholder="0" value={weight} onChange={e=>setWeight(e.target.value)}/></label>}<label><span>{trackingFor(exercise)==='timed'?'Süre (saniye)':'Tekrar'}</span><input required autoComplete="off" inputMode="numeric" placeholder={trackingFor(exercise)==='timed'?'30':'12'} value={reps} onChange={e=>setReps(e.target.value)}/></label></div><button className="primary wide" type="submit"><Plus size={20}/> Seti kaydet</button></form><button className="textbtn wide" onClick={()=>setSelected(null)}>Başka hareket seç</button></DialogContent></Dialog>}
 {adding&&<Dialog open onOpenChange={setAdding}><DialogContent className="sheet" showCloseButton={false} aria-describedby={undefined}><div className="sheethead"><DialogTitle id="add-title">Yeni hareket</DialogTitle><button className="icon" aria-label="Kapat" onClick={()=>setAdding(false)}><X/></button></div><p className="sub">{group} listesine kaydedilecek.</p><form onSubmit={e=>{e.preventDefault();addExercise()}}><label className="formfield">Hareket veya makine adı<input required maxLength={80} placeholder="Örn. Lat Pulldown — tek makara" value={name} onChange={e=>setName(e.target.value)}/></label><div className="formfield">Kayıt türü<Choice label="Yeni hareket kayıt türü" value={newTracking} items={trackingOptions} onChange={v=>setNewTracking(v as TrackingMode)}/></div>{group===matGroup&&<label className="formfield">Kas bölgesi<select value={newGroup} onChange={e=>setNewGroup(e.target.value)}>{groups.map(g=><option key={g}>{g}</option>)}</select></label>}{newTracking==='weighted'&&<label className="formfield">Ağırlığı nasıl gireceksin?<select value={unit} onChange={e=>setUnit(e.target.value)}>{['Makinede görünen','Tek dambıl','Bar dâhil toplam','Ek ağırlık'].map(u=><option key={u}>{u}</option>)}</select></label>}<PhotoPicker value={newPhoto} onChange={setNewPhoto} onBusyChange={setPhotoBusy}/><button className="primary wide" type="submit" disabled={photoBusy}>Hareketi ekle</button></form></DialogContent></Dialog>}
 {settings&&<Dialog open onOpenChange={setSettings}><DialogContent className="sheet" showCloseButton={false} aria-describedby={undefined}><div className="sheethead"><DialogTitle id="settings-title">Kayıtlar ve kurulum</DialogTitle><button className="icon" aria-label="Kapat" onClick={()=>setSettings(false)}><X/></button></div><div className="infobox"><h3>Profil ve kalori hesabı</h3><p>{profile?`${profile.weight} kg · ${profile.height} cm · ${profile.age} yaş`:"Kalori tahmini için bilgilerini ekle."}</p><button className="outline wide" onClick={()=>{setSettings(false);setProfileOpen(true)}}><UserRound size={18}/> {profile?"Bilgilerimi güncelle":"Profilimi oluştur"}</button><p>Profil güncellemeleri eski antrenmanlarının kalori hesabını değiştirmez.</p></div><div className="infobox"><h3>iPhone’a ekle</h3><p>Safari’de bu sayfayı aç. Paylaş menüsünden “Ana Ekrana Ekle”yi seç. İlk açılışı internet bağlantısıyla yap.</p></div><div className="infobox"><h3>Bulut yedeği ve telefon alanı</h3><p>Kayıtların bağlantı varken hesabına yedeklenir. Bu yedek iCloud’dan ayrıdır. İnternetsiz kullanım için telefonda küçük bir kopya tutulur.</p><p>Antrenman kayıtları: <strong>{n(new Blob([JSON.stringify({records,pending:pending.current})]).size/1024)} KB</strong>. Uygulamanın açılış dosyaları ayrıca yer kaplar.</p></div><div className="infobox"><h3>İnternetsiz antrenman</h3><p>{offlineReady?'Çevrimdışı destek etkin. İlk kullanımda sayfanın tamamen yüklenmesini bekle.':'Çevrimdışı destek hazırlanıyor; ilk açılış için internet gerekiyor.'} Kayıtlar bu telefonda bekler, bağlantı gelince hesabına yedeklenir. Bekleyen kayıtlar varken Safari verilerini silme.</p><p>Durum: {status}</p><button className="outline" onClick={()=>void sync()}>Şimdi yedekle</button></div><div className="infobox"><h3>iCloud Drive’a ek yedek</h3><p>“Dosyalara kaydet” düğmesine dokun. Açılan paylaşım menüsünden “Dosyalara Kaydet”, ardından “iCloud Drive”ı seç. Bu işlem elle alınan bir yedektir; otomatik iCloud eşitlemesi değildir.</p><button className="outline wide" onClick={()=>void exportToFiles()}><Upload size={18}/> Dosyalara kaydet</button></div><button className="outline wide" onClick={()=>download(JSON.stringify({version:1,records:current.current},null,2),'application/json','set-defteri-yedek.json')}><Download size={18}/> Yedeği dosya olarak indir</button><button className="outline wide" onClick={()=>file.current?.click()}><Upload size={18}/> Yedekten geri yükle</button><input hidden type="file" accept="application/json,.json" ref={file} onChange={e=>void restore(e.target.files?.[0])}/><p className="sub">Farklı makineleri ayırmak için her birini yeni hareket olarak ekleyebilirsin.</p></DialogContent></Dialog>}
 {purgeExercise&&<DeleteExercise permanent exercise={purgeExercise} onClose={()=>setPurgeExercise(null)} onDelete={()=>{if(save(removeExercisePermanently(purgeExercise))){setPurgeExercise(null);setNotice('Hareket silinenler listesinden de kaldırıldı; geçmiş kayıtların korundu')}}}/>}
 {removeExercise&&<DeleteExercise exercise={removeExercise} onClose={()=>setRemoveExercise(null)} onDelete={()=>{if(save({...removeExercise,archived:true})){setRemoveExercise(null);setNotice('Hareket listeden silindi; eski antrenmanların korundu')}}}/>}
 {editing&&<WorkoutEditor key={editing.id} workout={editing} exercises={exercises} onClose={()=>setEditId(null)} onSave={w=>{if(save(w)){setEditId(null);setNotice('Antrenman güncellendi; raporlar yeniden hesaplandı')}}}/>}
 {deleting&&<DeleteWorkout workout={deleting} onClose={()=>setDeleteId(null)} onDelete={()=>deleteWorkout(deleting)}/>}
 {profileOpen&&<ProfilePanel profile={profile} onClose={()=>{setProfileOpen(false);if(!profile){setCardioOpen(false);setFinishId(null)}}} onSave={p=>{if(save(p)){setProfileOpen(false);setNotice('Profil kaydedildi')}}}/>}
 {cardioOpen&&!profileOpen&&<CardioPanel profile={profile} onClose={()=>setCardioOpen(false)} onSave={saveCardio}/>}
 {finishing&&profile&&!profileOpen&&<FinishPanel exercises={exercises} workout={finishing} profile={profile} onClose={()=>setFinishId(null)} onSave={complete}/>}
 {notice&&<div role="status" className="toast"><Check size={18}/>{notice}</div>}
 </div>
}
