'use client';
import {EnergyFields,validEnergyDuration} from './session-energy';
import {useState} from 'react';
import {BodyMap} from '@/components/body-map';
import type {Exercise} from '@/lib/exercises';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Flame,X,UserRound} from 'lucide-react';
import {activeCalories,caloriesFor,cardioTypes,dailyCalories,strengthOptions,isRecord,type CalorieInfo,type Profile,type Cardio,type Workout} from '@/lib/training';
const fmt=(v:number)=>v.toLocaleString('tr-TR',{maximumFractionDigits:0});
export function Choice({value,onChange,items,label}:{value:string;onChange:(value:string)=>void;items:{id:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="training-select" aria-label={label}><SelectValue/></SelectTrigger><SelectContent className="training-options" position="popper">{items.map(i=><SelectItem key={i.id} value={i.id}>{i.label}</SelectItem>)}</SelectContent></Select>}
export function ProfilePanel({profile,onSave,onClose}:{profile?:Profile;onSave:(p:Profile)=>void;onClose:()=>void}){
 const [weight,setWeight]=useState(profile?String(profile.weight):''),[height,setHeight]=useState(profile?String(profile.height):''),[age,setAge]=useState(profile?String(profile.age):''),[error,setError]=useState('');
 function submit(e:React.FormEvent){e.preventDefault();const p:Profile={id:'user-profile-v1',kind:'profile',weight:Number(weight.replace(',','.')),height:Number(height.replace(',','.')),age:Number(age),updated:0};if(!isRecord(p)){setError('Kilo 20–400 kg, boy 100–250 cm ve yaş 18–100 aralığında olmalı.');return}onSave(p)}
 return <Dialog open onOpenChange={o=>{if(!o)onClose()}}><DialogContent className="sheet" showCloseButton={false} aria-describedby={undefined}><div className="sheethead"><DialogTitle>Önce seni tanıyalım</DialogTitle><button className="icon" aria-label="Kapat" onClick={onClose}><X/></button></div><p className="sub">Kalori tahmini için güncel bilgilerini gir. Sonradan ayarlardan değiştirebilirsin.</p><form onSubmit={submit}><div className="profile-grid"><label className="formfield">Kilo (kg)<input required inputMode="decimal" placeholder="Örn. 96" value={weight} onChange={e=>setWeight(e.target.value)}/></label><label className="formfield">Boy (cm)<input required inputMode="decimal" placeholder="Örn. 175" value={height} onChange={e=>setHeight(e.target.value)}/></label><label className="formfield">Yaş<input required inputMode="numeric" placeholder="Örn. 25" value={age} onChange={e=>setAge(e.target.value)}/></label></div><p className="method-note">Kalori tahmini kilo, süre ve aktivite temposuna dayanır. Boy ve yaş profilinde saklanır; bu standart MET hesabına doğrudan girmez.</p>{error&&<p role="alert" className="formerror">{error}</p>}<button type="submit" className="primary wide"><UserRound size={18}/> Bilgilerimi kaydet</button></form></DialogContent></Dialog>
}
export function CardioPanel({onSave,onClose,profile}:{onSave:(c:Cardio)=>void;onClose:()=>void;profile?:Profile}){
 const [type,setType]=useState('walking'),[optionId,setOption]=useState('walk-medium'),[minutes,setMinutes]=useState(''),[error,setError]=useState('');
 const activity=cardioTypes.find(t=>t.id===type)!;const option=activity.options.find(o=>o.id===optionId)!;const duration=Number(minutes.replace(',','.'));
 return <Dialog open onOpenChange={o=>{if(!o)onClose()}}><DialogContent className="sheet" showCloseButton={false} aria-describedby={undefined}><div className="sheethead"><DialogTitle>Kardiyo ekle</DialogTitle><button className="icon" aria-label="Kapat" onClick={onClose}><X/></button></div><form onSubmit={e=>{e.preventDefault();if(!Number.isFinite(duration)||duration<1||duration>600){setError('1–600 dakika arasında bir süre gir.');return}onSave({id:crypto.randomUUID(),type,label:activity.label,optionId,effort:option.label,met:option.met,minutes:duration})}}><div className="formfield">Aktivite<Choice label="Kardiyo türü" value={type} onChange={v=>{setType(v);setOption(cardioTypes.find(t=>t.id===v)!.options[0].id)}} items={cardioTypes}/></div><div className="formfield">Tempo / koşul<Choice label="Tempo ve koşul" value={optionId} onChange={setOption} items={activity.options}/></div><label className="formfield">Süre (dakika)<input required inputMode="decimal" placeholder="Örn. 25" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><p className="sub">Molaları çıkararak hareket ettiğin süreyi gir. Tempoyu değiştirirsen ayrı bir kardiyo kaydı ekleyebilirsin.</p>{profile&&duration>0&&duration<=600&&<div className="calorie-preview"><Flame size={24}/><div><strong>≈ {fmt(activeCalories(option.met,profile.weight,duration))} kcal</strong><small>Tahmini aktif kalori · {profile.weight} kg</small></div></div>}{!profile&&<p className="method-note">Kalori tahmini için profil bilgilerini eklemen gerekiyor.</p>}{error&&<p className="formerror" role="alert">{error}</p>}<button className="primary wide" type="submit">Kardiyoyu kaydet</button></form></DialogContent></Dialog>
}
export function FinishPanel({workout,profile,onSave,onClose,exercises}:{exercises:Exercise[];workout:Workout;profile:Profile;onSave:(w:Workout)=>void;onClose:()=>void}){
 const [calorie,setCalorie]=useState<CalorieInfo>(()=>({...workout.calorie,method:'met-net-v2',weight:workout.calorie?.weight||profile.weight,height:workout.calorie?.height||profile.height,age:workout.calorie?.age||profile.age,strengthMinutes:workout.calorie?.strengthMinutes||0,strengthMet:workout.calorie?.strengthMet||3.5,matMinutes:workout.calorie?.matMinutes||0,matMet:workout.calorie?.matMet||2.8}));
 const [error,setError]=useState('');
 const candidate:Workout={...workout,ended:workout.ended||new Date().toISOString(),calorie};
 const valid=isRecord(candidate)&&validEnergyDuration(candidate);const estimate=valid?caloriesFor(candidate):null;
 return <Dialog open onOpenChange={o=>{if(!o)onClose()}}><DialogContent className="sheet" showCloseButton={false} aria-describedby={undefined}><div className="sheethead"><DialogTitle>{workout.ended?'Kalori bilgisi':'Antrenman özeti'}</DialogTitle><button className="icon" aria-label="Kapat" onClick={onClose}><X/></button></div><p className="sub">Ağırlık, mat ve kardiyo sürelerini ayrı hesaplayalım. Her dakikayı yalnızca bir bölüme yaz.</p><form onSubmit={e=>{e.preventDefault();if(!valid){setError('Geçerli kilo ve süre gir. Set kaydın varsa ağırlık veya mat süresi sıfırdan büyük, toplamı en fazla 600 dk olmalı.');return}onSave(candidate)}}><EnergyFields value={calorie} onChange={setCalorie} workout={workout}/>{!!workout.cardio?.length&&<p className="sub">Kardiyo: {workout.cardio.map(c=>`${c.label} ${c.minutes} dk`).join(' · ')}</p>}{estimate&&<div className="calorie-preview"><Flame size={30}/><div><strong>≈ {fmt(estimate.total)} kcal</strong><small>Tahmini aktif kalori · {estimate.minutes.toLocaleString('tr-TR')} dk</small><small>Ağırlık: {estimate.resistance} · Mat / vücut ağırlığı: {estimate.mat} · Kardiyo: {estimate.cardio} kcal</small></div></div>}<MethodNote/>{error&&<p role="alert" className="formerror">{error}</p>}<button type="submit" className="primary wide">{workout.ended?'Kalori bilgisini kaydet':'Antrenmanı tamamla'}</button></form><BodyMap workout={workout} exercises={exercises}/></DialogContent></Dialog>
}
export function MethodNote(){return <details className="method-details"><summary>Kalori nasıl hesaplanıyor?</summary><p>2024 Adult Compendium MET değerleri kullanılır. Aktif kcal = (MET − 1) × 3,5 × kilo / 200 × dakika. Dinlenirken harcanacak enerji çıkarılır; bu sayı günlük toplam kalorin değildir.</p><p>Boy ve yaş bu formüle doğrudan girmez. Hareket başına kilo × tekrar, kaloriye doğrudan çevrilmez. Aynı süre ve eforda hareket değiştirmen tahmini değiştirmeyebilir. Kalp atışı, kondisyon, teknik ve bireysel metabolizma ölçülmez. Sonuç yaklaşık bir tahmindir; özellikle 19–59 yaş dışındaki kişilerde belirsizlik artar.</p><p><a href="https://pacompendium.com/" target="_blank" rel="noreferrer">Kaynak: Compendium of Physical Activities</a></p></details>}
export function CalorieReport({workouts}:{workouts:Workout[]}){
 const points=dailyCalories(workouts).slice(-10);const missing=workouts.filter(w=>w.ended&&!w.deleted&&!w.calorie).length;const max=Math.max(1,...points.map(p=>p.total));const recent=workouts.filter(w=>w.ended&&!w.deleted&&Date.now()-new Date(w.date).getTime()<7*86400000);const total=recent.reduce((s,w)=>s+(caloriesFor(w)?.total||0),0);
 return <section className="reportcard calorie-report"><div className="sectionhead"><h2>Kalori değişimi</h2><Flame size={22}/></div><p className="sub">Ağırlık + mat / vücut ağırlığı + kardiyo = günlük tahmini aktif kalori. Tamamlanan antrenmanlar birlikte toplanır.</p><div className="calorie-total"><span>SON 7 GÜN · KAYITLI TAHMİNLER</span><strong>≈ {fmt(total)} <small>kcal</small></strong></div>{points.length?<><div className="calorie-chart-scroll"><div className="chart calorie-chart" role="img" aria-label={points.map(p=>`${new Date(p.date).toLocaleDateString('tr-TR')}: ${p.total} tahmini aktif kilokalori`).join('; ')}>{points.map(p=><div className="barcol" key={p.key}><strong>{fmt(p.total)}</strong><div className="bar" style={{height:Math.max(4,p.total/max*130)}}/><small>{new Date(p.date).toLocaleDateString('tr-TR',{day:'numeric',month:'numeric'})}</small></div>)}</div></div><div className="reportrows">{points.slice().reverse().map(p=><div key={p.key}><span>{new Date(p.date).toLocaleDateString('tr-TR',{day:'numeric',month:'long'})}</span><strong>≈ {fmt(p.total)} kcal<small className="calorie-breakdown">Kuvvet / mat {fmt(p.strength)} + kardiyo {fmt(p.cardio)}</small></strong></div>)}</div></>:<div className="empty compact"><Flame size={32}/><p>Antrenmanı süre bilgisiyle tamamladığında grafiğin burada oluşacak.</p></div>}{missing>0&&<p className="method-note">{missing} eski antrenmanda kalori bilgisi yok; sıfır olarak sayılmadı. Geçmişten süre ve kilo ekleyebilirsin.</p>}<MethodNote/></section>
}
