// Original, unattributed copy. Bundled locally so the daily message needs no network.
export const messages=[
 'Bugün attığın küçük adım, yarının güçlü başlangıcı.',
 'Kendine verdiğin sözü bir setle tut.',
 'Her tekrar, emeğinin bir satırı.',
 'Dünkü senin bıraktığı yerden devam et.',
 'Güç, tekrar tekrar geri gelmekte.',
 'Bugün burada olman bile bir başlangıç.',
 'Acele etme. Kendi ritminde güçlen.',
 'Küçük ilerlemeler bir gün büyük fark yaratır.',
 'Bugünün emeğini gelecekteki sen hissedecek.',
 'Bir set. Bir adım. Biraz daha sen.',
 'Başlamak için kusursuz bir gün bekleme.',
 'İlerlemenin ölçüsü bazen sadece devam etmektir.',
 'Kendi yolunda, kendi hızında.',
 'Bugün kendine ayırdığın zaman kıymetli.',
 'Sonuca giden yol, bugünkü tekrarından geçiyor.',
 'Gücünü sabırla inşa et.',
 'Her antrenman, kendine yeni bir şans.',
 'İstikrar, küçük adımların toplamı.',
 'Bugün yapabildiğin, bugün için değerlidir.',
 'Bir önceki kaydın, yeni başlangıç noktan.',
 'Gelişim her gün rekor kırmak değildir.',
 'Kendinle yarış. Emeğini fark et.',
 'İlk tekrarı yap. Gerisi adım adım gelir.',
 'Bugün bir tuğla daha koy.',
 'Güçlü alışkanlıklar, küçük seçimlerle başlar.',
 'Yol uzun olabilir. Bugünkü adım senin.',
 'Daha ağır değilse, daha kontrollü.',
 'Bedenini dinle. Emeğine güven.',
 'Hedefini hatırla, bugüne odaklan.',
 'İyi bir başlangıç bazen sadece gelmektir.',
 'Kendine yatırım yapmanın tam zamanı.',
 'Her gün aynı hissetmesen de yolun devam eder.',
 'Kıyaslamayı bırak. Kendi gelişimini izle.',
 'Bugünkü çaban, geleceğine bir not.',
 'Bir adım daha atabilecek kadar buradasın.',
 'Düzenli emek, sessizce fark yaratır.',
 'Gücün kadar sabrını da geliştir.',
 'Önemli olan, yeniden başlayabilmek.',
 'Büyük hedefini küçük setlere böl.',
 'Bugün kendi hikâyene bir sayfa ekle.',
 'Emek verdiğin her gün birikir.',
 'Kusursuzluk değil, sürdürebildiğin ritim.',
 'Buradasın. Şimdi ilk sete odaklan.',
 'Gelişim, kendine gösterdiğin özenle başlar.',
 'İyi form, sağlam bir başlangıçtır.',
 'Bugünün küçük zaferini kaydet.',
 'Güç bazen bir tekrar, bazen biraz dinlenmektir.',
 'Kendi sınırlarını zamanla tanı.',
 'Dünün emeği geride kalmadı; seninle geliyor.',
 'Bir hedef, birçok küçük başlangıç.',
 'Önce nefes al. Sonra kendine odaklan.',
 'Buraya gelmek bir karar. Devam etmek bir alışkanlık.',
 'Küçük farkları küçümseme.',
 'Bugün yapabildiğin en iyi başlangıcı yap.',
 'Her setinde biraz daha deneyim birikir.',
 'İlerlemen bazen sayılardan daha fazlasıdır.',
 'Kendine ayırdığın bu zamanı sahiplen.',
 'Ritmini bul. Adımlarını biriktir.',
 'Yavaş ilerlemek de ilerlemektir.',
 'Bir gün değil, gün gün güçlen.',
];
export function dailyMotivation(date=new Date()){
 const day=Math.floor(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())/86400000);
 const index=((day%messages.length)+messages.length)%messages.length;
 return {key:`${date.getFullYear()}-${date.getMonth()+1}-${date.getDate()}`,text:messages[index]};
}
